version: "3.8"

networks:
  selenoid:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8082:8080"   # Jenkins UI
      - "50000:50000" # Для агентов
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    restart: unless-stopped
    ports:
      - "8080:8080"  # UI для просмотра браузеров
    networks:
      - selenoid
    depends_on:
      - selenoid

volumes:
  jenkins_home:
  selenoid_config:
  selenoid_logs:
